<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>4.1.1</version>
        <relativePath/>
    </parent>

    <groupId>io.github.doctor277.launchguard</groupId>
    <artifactId>launchguard-parent</artifactId>
    <version>1.0.0</version>
    <packaging>pom</packaging>
    <name>LaunchGuard</name>
    <description>Service health monitoring platform</description>

    <modules>
        <module>monitoring-events</module>
        <module>probe-worker</module>
        <module>backend</module>
        <module>demo-services/payment-service</module>
        <module>demo-services/order-service</module>
        <module>demo-services/notification-service</module>
    </modules>

    <properties>
        <java.version>25</java.version>
        <maven.compiler.release>25</maven.compiler.release>
        <aws-msk-iam-auth.version>2.3.8</aws-msk-iam-auth.version>
    </properties>
</project>
